### ISSUE TITLE
remove retard

### ISSUE THREAD

**Issue by xBrownieCodezV2** [VerusAC/VerusAntiCheat#13]
remove @SlawPing this fucking retard he does fucking broken and shit commits

example https://img.mdma.dev/5Z7lJXp.png

there is fucking number obfuscation everywhere

**Comment by Izibane** [comment]
@SlawPing stop breaking the repo dickhead

**Comment by AkramLZ** [comment]
> remove @SlawPing this fucking retard he does fucking broken and shit commits
> 
> example https://img.mdma.dev/5Z7lJXp.png
> 
> there is fucking number obfuscation everywhere

which class is that?

**Comment by AkramLZ** [comment]
nvm i found it, he pushed it accidently

**Comment by AkramLZ** [comment]
@SlawPing lick my balls

**Comment by xBrownieCodezV2** [comment]
> @SlawPing lick my balls

please remove him his commits are useless

**Comment by AkramLZ** [comment]
removed
